#ifndef PAPACC_RUNTIME_LOG_H
#define PAPACC_RUNTIME_LOG_H

#include "papacc/types.h"

#define PAPACC_LOG_ENDPOINT_TEXT_CAPACITY 64U
#define PAPACC_LOG_PROVIDER_ID_CAPACITY 32U

typedef enum PAPACC_LOG_LEVEL {
    /* Local process contract; these values are not a cross-project or wire ABI. */
    PAPACC_LOG_LEVEL_OFF = 0,
    PAPACC_LOG_ERROR = 1,
    PAPACC_LOG_WARNING = 2,
    PAPACC_LOG_INFO = 3,
    PAPACC_LOG_DEBUG = 4,
    PAPACC_LOG_TRACE = 5
} PAPACC_LOG_LEVEL;

typedef enum PAPACC_LOG_EVENT_ID {
    PAPACC_LOG_EVENT_UNSPECIFIED = 0,
    PAPACC_LOG_EVENT_RUNTIME_STARTED,
    PAPACC_LOG_EVENT_RUNTIME_STOPPED,
    PAPACC_LOG_EVENT_SERVER_STARTED,
    PAPACC_LOG_EVENT_SERVER_STOPPING,
    PAPACC_LOG_EVENT_CONNECTION_ACCEPTED,
    PAPACC_LOG_EVENT_CONNECTION_REJECTED,
    PAPACC_LOG_EVENT_CONTROL_ESTABLISHED,
    PAPACC_LOG_EVENT_DATA_CONNECTION_ACCEPTED,
    PAPACC_LOG_EVENT_DATA_TICKET_ISSUED,
    PAPACC_LOG_EVENT_DATA_ATTACHED,
    PAPACC_LOG_EVENT_CHANNEL_CLOSED,
    PAPACC_LOG_EVENT_SESSION_CLEANUP,
    PAPACC_LOG_EVENT_PROTOCOL_REJECTED,
    PAPACC_LOG_EVENT_DATA_TICKETS_EXPIRED,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_RUNTIME_READY,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_RUNTIME_FAILURE,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_CONNECTION_SECURE,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_CONNECTION_FAILURE,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_AUTHENTICATION_FAILURE,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_CONNECTION_CLOSED,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_STATE_TRANSITION,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_OPERATION_PROGRESS,
    PAPACC_LOG_EVENT_SECURE_TRANSPORT_UNRECOGNIZED
} PAPACC_LOG_EVENT_ID;

typedef enum PAPACC_LOG_CATEGORY {
    PAPACC_LOG_CATEGORY_UNSPECIFIED = 0,
    PAPACC_LOG_CATEGORY_RUNTIME,
    PAPACC_LOG_CATEGORY_NETWORK,
    PAPACC_LOG_CATEGORY_PROTOCOL,
    PAPACC_LOG_CATEGORY_SESSION,
    PAPACC_LOG_CATEGORY_SECURITY,
    PAPACC_LOG_CATEGORY_BACKEND
} PAPACC_LOG_CATEGORY;

typedef enum PAPACC_LOG_COMPONENT_ID {
    PAPACC_LOG_COMPONENT_UNSPECIFIED = 0,
    PAPACC_LOG_COMPONENT_RUNTIME,
    PAPACC_LOG_COMPONENT_SERVER,
    PAPACC_LOG_COMPONENT_SERVER_IO_LOOP,
    PAPACC_LOG_COMPONENT_SECURE_TRANSPORT
} PAPACC_LOG_COMPONENT_ID;

typedef enum PAPACC_LOG_OPERATION {
    PAPACC_LOG_OPERATION_UNSPECIFIED = 0,
    PAPACC_LOG_OPERATION_STARTUP,
    PAPACC_LOG_OPERATION_SHUTDOWN,
    PAPACC_LOG_OPERATION_ACCEPT,
    PAPACC_LOG_OPERATION_ESTABLISH,
    PAPACC_LOG_OPERATION_ATTACH,
    PAPACC_LOG_OPERATION_ISSUE,
    PAPACC_LOG_OPERATION_CLEANUP,
    PAPACC_LOG_OPERATION_EXPIRE,
    PAPACC_LOG_OPERATION_CONFIGURE,
    PAPACC_LOG_OPERATION_TRANSPORT,
    PAPACC_LOG_OPERATION_CONNECTION,
    PAPACC_LOG_OPERATION_HANDSHAKE,
    PAPACC_LOG_OPERATION_AUTHENTICATION,
    PAPACC_LOG_OPERATION_READ,
    PAPACC_LOG_OPERATION_WRITE,
    PAPACC_LOG_OPERATION_WAIT
} PAPACC_LOG_OPERATION;

typedef enum PAPACC_LOG_SECURE_TRANSPORT_ROLE {
    PAPACC_LOG_SECURE_TRANSPORT_ROLE_UNKNOWN = 0,
    PAPACC_LOG_SECURE_TRANSPORT_ROLE_CLIENT,
    PAPACC_LOG_SECURE_TRANSPORT_ROLE_SERVER
} PAPACC_LOG_SECURE_TRANSPORT_ROLE;

typedef enum PAPACC_LOG_KNOWN_FACT {
    PAPACC_LOG_KNOWN_FACT_UNKNOWN = 0,
    PAPACC_LOG_KNOWN_FACT_FALSE,
    PAPACC_LOG_KNOWN_FACT_TRUE,
    PAPACC_LOG_KNOWN_FACT_UNSUPPORTED,
    PAPACC_LOG_KNOWN_FACT_NOT_APPLICABLE
} PAPACC_LOG_KNOWN_FACT;

#define PAPACC_LOG_CONTEXT_CONNECTION_ID 0x00000001UL
#define PAPACC_LOG_CONTEXT_SESSION_ID 0x00000002UL
#define PAPACC_LOG_CONTEXT_CHANNEL_ID 0x00000004UL
#define PAPACC_LOG_CONTEXT_LOCAL_ENDPOINT 0x00000008UL
#define PAPACC_LOG_CONTEXT_REMOTE_ENDPOINT 0x00000010UL
#define PAPACC_LOG_CONTEXT_SECURE_TRANSPORT_ROLE 0x00000020UL
#define PAPACC_LOG_CONTEXT_PROVIDER_ID 0x00000040UL
#define PAPACC_LOG_CONTEXT_PEER_AUTH_FACT 0x00000080UL
#define PAPACC_LOG_CONTEXT_POLICY_FACT 0x00000100UL
#define PAPACC_LOG_CONTEXT_SOURCE_RESULT 0x00000200UL

typedef struct PAPACC_LOG_CONTEXT {
    PAPACC_U32 fields;
    PAPACC_U64 connection_instance_id;
    PAPACC_U64 session_instance_id;
    PAPACC_U64 channel_instance_id;
    char local_endpoint[PAPACC_LOG_ENDPOINT_TEXT_CAPACITY];
    char remote_endpoint[PAPACC_LOG_ENDPOINT_TEXT_CAPACITY];
    PAPACC_LOG_SECURE_TRANSPORT_ROLE secure_transport_role;
    char provider_id[PAPACC_LOG_PROVIDER_ID_CAPACITY];
    PAPACC_LOG_KNOWN_FACT peer_auth_fact;
    PAPACC_LOG_KNOWN_FACT policy_fact;
    PAPACC_I32 source_result;
} PAPACC_LOG_CONTEXT;

#define PAPACC_LOG_CONTEXT_INITIALIZER \
    { 0, 0, 0, 0, {0}, {0}, PAPACC_LOG_SECURE_TRANSPORT_ROLE_UNKNOWN, \
      {0}, PAPACC_LOG_KNOWN_FACT_UNKNOWN, PAPACC_LOG_KNOWN_FACT_UNKNOWN, 0 }

typedef struct PAPACC_LOG_RECORD {
    PAPACC_LOG_LEVEL level;
    PAPACC_LOG_EVENT_ID event_id;
    PAPACC_LOG_CATEGORY category;
    PAPACC_LOG_COMPONENT_ID component_id;
    PAPACC_LOG_OPERATION operation;
    PAPACC_RESULT result;
    PAPACC_BOOL result_valid;
    const char *message;
    PAPACC_LOG_CONTEXT context;
    PAPACC_U64 monotonic_timestamp_ns;
    PAPACC_BOOL monotonic_timestamp_valid;
} PAPACC_LOG_RECORD;

typedef void (*PAPACC_LOG_SINK_FN)(void *context,
    const PAPACC_LOG_RECORD *record);

typedef struct PAPACC_LOGGER {
    PAPACC_LOG_SINK_FN sink;
    void *sink_context;
    PAPACC_LOG_LEVEL minimum_level;
} PAPACC_LOGGER;

PAPACC_RESULT papacc_logger_init(PAPACC_LOGGER *logger,
    PAPACC_LOG_SINK_FN sink, void *sink_context,
    PAPACC_LOG_LEVEL minimum_level);

/*
 * Delivery is synchronous. The record and message are borrowed and valid only
 * during the callback; a retaining consumer must copy them before returning.
 * Context is bounded and copied by value. Suppression happens before timestamp
 * acquisition and record construction. Logging never replaces caller results.
 */
void papacc_log_event(const PAPACC_LOGGER *logger, PAPACC_LOG_LEVEL level,
    PAPACC_LOG_EVENT_ID event_id, PAPACC_LOG_CATEGORY category,
    PAPACC_LOG_COMPONENT_ID component_id, PAPACC_LOG_OPERATION operation,
    PAPACC_BOOL result_valid, PAPACC_RESULT result,
    const PAPACC_LOG_CONTEXT *context, const char *message);

#endif
