#ifndef PAPACC_CONNECTION_CLASSIFIER_H
#define PAPACC_CONNECTION_CLASSIFIER_H

#include "connection.h"
#include "data_association_protocol.h"
#include "control_protocol.h"
#include "framed_reader.h"

typedef enum PAPACC_CONNECTION_CLASSIFICATION {
    PAPACC_CONNECTION_CLASSIFICATION_UNSPECIFIED = 0,
    PAPACC_CONNECTION_CLASSIFICATION_CONTROL = 1,
    PAPACC_CONNECTION_CLASSIFICATION_DATA = 2
} PAPACC_CONNECTION_CLASSIFICATION;

typedef enum PAPACC_CONNECTION_CLASSIFIER_STATE {
    PAPACC_CONNECTION_CLASSIFIER_STATE_UNINITIALIZED = 0,
    PAPACC_CONNECTION_CLASSIFIER_STATE_WAITING_FIRST_HEADER = 1,
    PAPACC_CONNECTION_CLASSIFIER_STATE_CLASSIFIED_CONTROL = 2,
    PAPACC_CONNECTION_CLASSIFIER_STATE_CLASSIFIED_DATA = 3,
    PAPACC_CONNECTION_CLASSIFIER_STATE_CLOSED = 4,
    PAPACC_CONNECTION_CLASSIFIER_STATE_ERROR = 5
} PAPACC_CONNECTION_CLASSIFIER_STATE;

typedef enum PAPACC_CONNECTION_CLASSIFIER_STATUS {
    PAPACC_CONNECTION_CLASSIFIER_STATUS_UNSPECIFIED = 0,
    PAPACC_CONNECTION_CLASSIFIER_STATUS_PROGRESS = 1,
    PAPACC_CONNECTION_CLASSIFIER_STATUS_WOULD_BLOCK = 2,
    PAPACC_CONNECTION_CLASSIFIER_STATUS_CLASSIFIED_CONTROL = 3,
    PAPACC_CONNECTION_CLASSIFIER_STATUS_CLASSIFIED_DATA = 4,
    PAPACC_CONNECTION_CLASSIFIER_STATUS_CLOSED = 5
} PAPACC_CONNECTION_CLASSIFIER_STATUS;

typedef struct PAPACC_CONNECTION_CLASSIFIER {
    PAPACC_CONNECTION_MANAGER *connection_manager;
    PAPACC_CONNECTION *connection;
    PAPACC_FRAMED_READER reader;
    PAPACC_FRAME_HEADER first_header;
    PAPACC_U64 establishment_deadline_ns;
    PAPACC_CONNECTION_CLASSIFIER_STATE state;
} PAPACC_CONNECTION_CLASSIFIER;

#define PAPACC_CONNECTION_CLASSIFIER_INITIALIZER \
    { NULL, NULL, PAPACC_FRAMED_READER_INITIALIZER, \
      PAPACC_FRAME_HEADER_INITIALIZER, 0, \
      PAPACC_CONNECTION_CLASSIFIER_STATE_UNINITIALIZED }

PAPACC_RESULT papacc_connection_classifier_init(
    PAPACC_CONNECTION_CLASSIFIER *classifier,
    PAPACC_CONNECTION_MANAGER *connection_manager,
    PAPACC_U64 connection_instance_id, PAPACC_U8 *read_scratch,
    PAPACC_SIZE read_scratch_capacity, PAPACC_U32 max_payload_length,
    PAPACC_U64 establishment_deadline_ns);
PAPACC_RESULT papacc_connection_classifier_read_once(
    PAPACC_CONNECTION_CLASSIFIER *classifier,
    PAPACC_CONNECTION_CLASSIFIER_STATUS *out_status);
PAPACC_RESULT papacc_connection_classifier_check_deadline(
    PAPACC_CONNECTION_CLASSIFIER *classifier, PAPACC_U64 now_ns,
    PAPACC_CONNECTION_CLASSIFIER_STATUS *out_status);
PAPACC_RESULT papacc_connection_classifier_take(
    PAPACC_CONNECTION_CLASSIFIER *classifier,
    PAPACC_CONNECTION_CLASSIFICATION *out_classification,
    PAPACC_FRAME_HEADER *out_first_header, PAPACC_FRAMED_READER *out_reader,
    PAPACC_U64 *out_establishment_deadline_ns);
void papacc_connection_classifier_shutdown(
    PAPACC_CONNECTION_CLASSIFIER *classifier);

#endif
