#ifndef PAPACC_MESSAGE_TYPES_H
#define PAPACC_MESSAGE_TYPES_H

#include <papacc/types.h>

#define PAPACC_MESSAGE_TYPE_RESERVED ((PAPACC_U16)0x0000U)
#define PAPACC_MESSAGE_TYPE_CONTROL_OPEN ((PAPACC_U16)0x0001U)
#define PAPACC_MESSAGE_TYPE_CONTROL_ACCEPT ((PAPACC_U16)0x0002U)
#define PAPACC_MESSAGE_TYPE_DATA_TICKET_REQUEST ((PAPACC_U16)0x0003U)
#define PAPACC_MESSAGE_TYPE_DATA_TICKET ((PAPACC_U16)0x0004U)
#define PAPACC_MESSAGE_TYPE_DATA_ATTACH ((PAPACC_U16)0x0005U)
#define PAPACC_MESSAGE_TYPE_DATA_ACCEPT ((PAPACC_U16)0x0006U)

#endif
