#ifndef PAPACC_AUTHENTICATION_AUTHORIZATION_H
#define PAPACC_AUTHENTICATION_AUTHORIZATION_H

#include "papacc/types.h"

#define PAPACC_CREDENTIAL_SHA256_SIZE 32U
#define PAPACC_PRINCIPAL_VALUE_SIZE 16U

typedef struct PAPACC_PEER_EVIDENCE {
    PAPACC_BOOL certificate_present;
    PAPACC_BOOL chain_validated;
    PAPACC_BOOL peer_authenticated;
    PAPACC_BOOL certificate_sha256_valid;
    PAPACC_U8 certificate_sha256[PAPACC_CREDENTIAL_SHA256_SIZE];
} PAPACC_PEER_EVIDENCE;

typedef struct PAPACC_PRINCIPAL {
    PAPACC_BOOL valid;
    PAPACC_U8 value[PAPACC_PRINCIPAL_VALUE_SIZE];
} PAPACC_PRINCIPAL;

typedef enum PAPACC_PRINCIPAL_RESOLUTION {
    PAPACC_PRINCIPAL_RESOLVED = 0,
    PAPACC_PRINCIPAL_NOT_ENROLLED,
    PAPACC_PRINCIPAL_CREDENTIAL_DISABLED,
    PAPACC_PRINCIPAL_RESOLVER_ERROR
} PAPACC_PRINCIPAL_RESOLUTION;

typedef PAPACC_RESULT (*PAPACC_PRINCIPAL_RESOLVE_FN)(void *,
    const PAPACC_PEER_EVIDENCE *, PAPACC_PRINCIPAL_RESOLUTION *,
    PAPACC_PRINCIPAL *);

typedef enum PAPACC_AUTHORIZATION_ACTION {
    PAPACC_AUTHORIZATION_ACCESS_ACCELERATOR = 1,
    PAPACC_AUTHORIZATION_CREATE_CONTROL_SESSION = 2,
    PAPACC_AUTHORIZATION_ASSOCIATE_DATA = 3
} PAPACC_AUTHORIZATION_ACTION;

typedef enum PAPACC_AUTHORIZATION_DECISION {
    PAPACC_AUTHORIZATION_ALLOW = 0,
    PAPACC_AUTHORIZATION_DENY,
    PAPACC_AUTHORIZATION_ERROR
} PAPACC_AUTHORIZATION_DECISION;

typedef PAPACC_RESULT (*PAPACC_AUTHORIZATION_FN)(void *,
    const PAPACC_PRINCIPAL *, PAPACC_AUTHORIZATION_ACTION,
    PAPACC_AUTHORIZATION_DECISION *);

typedef enum PAPACC_SECURITY_CONTEXT_STATE {
    PAPACC_SECURITY_CONTEXT_UNAUTHENTICATED = 0,
    PAPACC_SECURITY_CONTEXT_AUTHENTICATING,
    PAPACC_SECURITY_CONTEXT_AUTHORIZED,
    PAPACC_SECURITY_CONTEXT_FAILED
} PAPACC_SECURITY_CONTEXT_STATE;

typedef struct PAPACC_CONNECTION_SECURITY_CONTEXT {
    PAPACC_SECURITY_CONTEXT_STATE state;
    PAPACC_PRINCIPAL principal;
} PAPACC_CONNECTION_SECURITY_CONTEXT;

typedef struct PAPACC_SESSION_SECURITY_CONTEXT {
    PAPACC_BOOL published;
    PAPACC_PRINCIPAL principal;
} PAPACC_SESSION_SECURITY_CONTEXT;

#define PAPACC_PEER_EVIDENCE_INITIALIZER { PAPACC_FALSE, PAPACC_FALSE, PAPACC_FALSE, PAPACC_FALSE, { 0 } }
#define PAPACC_PRINCIPAL_INITIALIZER { PAPACC_FALSE, { 0 } }
#define PAPACC_CONNECTION_SECURITY_CONTEXT_INITIALIZER { PAPACC_SECURITY_CONTEXT_UNAUTHENTICATED, PAPACC_PRINCIPAL_INITIALIZER }
#define PAPACC_SESSION_SECURITY_CONTEXT_INITIALIZER { PAPACC_FALSE, PAPACC_PRINCIPAL_INITIALIZER }

PAPACC_BOOL papacc_principal_equal(const PAPACC_PRINCIPAL *, const PAPACC_PRINCIPAL *);
PAPACC_RESULT papacc_authenticate_and_authorize(
    PAPACC_CONNECTION_SECURITY_CONTEXT *, const PAPACC_PEER_EVIDENCE *,
    PAPACC_PRINCIPAL_RESOLVE_FN, void *, PAPACC_AUTHORIZATION_FN, void *,
    PAPACC_AUTHORIZATION_ACTION, PAPACC_PRINCIPAL_RESOLUTION *,
    PAPACC_AUTHORIZATION_DECISION *);
PAPACC_RESULT papacc_session_security_context_publish(
    PAPACC_SESSION_SECURITY_CONTEXT *, const PAPACC_CONNECTION_SECURITY_CONTEXT *);
void papacc_connection_security_context_release(PAPACC_CONNECTION_SECURITY_CONTEXT *);
void papacc_session_security_context_release(PAPACC_SESSION_SECURITY_CONTEXT *);

#endif
