#ifndef PAPACC_SERVER_SECURITY_CONFIGURATION_H
#define PAPACC_SERVER_SECURITY_CONFIGURATION_H

#include "authentication_authorization.h"
#include "security_composition.h"

#define PAPACC_SECURITY_CONFIGURATION_REF_CAPACITY 64U

typedef struct PAPACC_SECURITY_CONFIGURATION_REF {
    PAPACC_BOOL valid;
    PAPACC_SIZE length;
    PAPACC_U8 value[PAPACC_SECURITY_CONFIGURATION_REF_CAPACITY];
} PAPACC_SECURITY_CONFIGURATION_REF;

#define PAPACC_SECURITY_CONFIGURATION_REF_INITIALIZER \
    { PAPACC_FALSE, 0U, { 0 } }

typedef enum PAPACC_SECURITY_CONFIGURATION_RESOLUTION {
    PAPACC_SECURITY_CONFIGURATION_RESOLVED = 0,
    PAPACC_SECURITY_CONFIGURATION_NOT_FOUND,
    PAPACC_SECURITY_CONFIGURATION_INVALID,
    PAPACC_SECURITY_CONFIGURATION_UNAVAILABLE,
    PAPACC_SECURITY_CONFIGURATION_RESOLVER_ERROR
} PAPACC_SECURITY_CONFIGURATION_RESOLUTION;

typedef void (*PAPACC_RESOLVED_SECURITY_RELEASE_FN)(void *context);

typedef struct PAPACC_RESOLVED_SERVER_SECURITY_CONFIGURATION {
    PAPACC_SECURITY_COMPOSITION_INPUTS composition_inputs;
    PAPACC_PRINCIPAL_RESOLVE_FN principal_resolve;
    void *principal_resolve_context;
    PAPACC_AUTHORIZATION_FN authorize;
    void *authorization_context;
    PAPACC_RESOLVED_SECURITY_RELEASE_FN release;
    void *release_context;
    PAPACC_BOOL valid;
} PAPACC_RESOLVED_SERVER_SECURITY_CONFIGURATION;

#define PAPACC_RESOLVED_SERVER_SECURITY_CONFIGURATION_INITIALIZER \
    { { NULL, 0U, NULL, 0U, NULL, 0U, NULL, 0U, NULL, NULL, NULL, NULL }, \
      NULL, NULL, NULL, NULL, NULL, NULL, PAPACC_FALSE }

typedef PAPACC_RESULT (*PAPACC_SECURITY_CONFIGURATION_RESOLVE_FN)(
    void *context, const PAPACC_SECURITY_CONFIGURATION_REF *reference,
    PAPACC_SECURITY_CONFIGURATION_RESOLUTION *resolution,
    PAPACC_RESOLVED_SERVER_SECURITY_CONFIGURATION *configuration);

PAPACC_RESULT papacc_security_configuration_ref_set(
    PAPACC_SECURITY_CONFIGURATION_REF *reference,
    const PAPACC_U8 *value, PAPACC_SIZE length);

PAPACC_BOOL papacc_security_configuration_ref_equal(
    const PAPACC_SECURITY_CONFIGURATION_REF *left,
    const PAPACC_SECURITY_CONFIGURATION_REF *right);

PAPACC_RESULT papacc_resolved_server_security_configuration_validate(
    const PAPACC_RESOLVED_SERVER_SECURITY_CONFIGURATION *configuration);

void papacc_resolved_server_security_configuration_release(
    PAPACC_RESOLVED_SERVER_SECURITY_CONFIGURATION *configuration);

PAPACC_RESULT papacc_server_security_configuration_resolve_and_compose(
    const PAPACC_SECURITY_CONFIGURATION_REF *reference,
    PAPACC_SECURITY_CONFIGURATION_RESOLVE_FN resolve, void *resolve_context,
    PAPACC_SECURITY_CONFIGURATION_RESOLUTION *resolution,
    PAPACC_RESOLVED_SERVER_SECURITY_CONFIGURATION *configuration,
    PAPACC_SECURITY_COMPOSITION *composition);

#endif
