#ifndef PAPACC_SERVER_LISTENER_CONFIGURATION_H
#define PAPACC_SERVER_LISTENER_CONFIGURATION_H

#include "persistent_bind_selection.h"
#include "server_security_configuration.h"

typedef enum PAPACC_LISTENER_TRANSPORT_PROFILE {
    PAPACC_LISTENER_TRANSPORT_PROFILE_UNSPECIFIED = 0,
    PAPACC_LISTENER_TRANSPORT_PROFILE_SECURE_PRINCIPAL,
    PAPACC_LISTENER_TRANSPORT_PROFILE_LEGACY_ENDPOINT
} PAPACC_LISTENER_TRANSPORT_PROFILE;

typedef struct PAPACC_SERVER_LISTENER_CONFIGURATION {
    PAPACC_PERSISTENT_BIND_SELECTION bind_selection;
    PAPACC_U16 port;
    PAPACC_LISTENER_TRANSPORT_PROFILE transport_profile;
    PAPACC_SECURITY_CONFIGURATION_REF security_configuration_ref;
} PAPACC_SERVER_LISTENER_CONFIGURATION;

#define PAPACC_SERVER_LISTENER_CONFIGURATION_INITIALIZER \
    { PAPACC_PERSISTENT_BIND_SELECTION_INITIALIZER, 0U, \
      PAPACC_LISTENER_TRANSPORT_PROFILE_UNSPECIFIED, \
      PAPACC_SECURITY_CONFIGURATION_REF_INITIALIZER }

typedef struct PAPACC_SERVER_LISTENER_CONFIGURATION_SET {
    const PAPACC_SERVER_LISTENER_CONFIGURATION *listeners;
    PAPACC_SIZE count;
} PAPACC_SERVER_LISTENER_CONFIGURATION_SET;

#define PAPACC_SERVER_LISTENER_CONFIGURATION_SET_INITIALIZER { NULL, 0U }

PAPACC_RESULT papacc_server_listener_configuration_validate(
    const PAPACC_SERVER_LISTENER_CONFIGURATION *listener);

PAPACC_RESULT papacc_server_listener_configuration_set_validate(
    const PAPACC_SERVER_LISTENER_CONFIGURATION_SET *configuration);

#endif
